service: ${file(../../common/config.yml):sevice}-vpc

custom: ${file(stages/${self:provider.stage}.yml)}

package:
  individually: true

projectDir: ../../

provider:
  name: aws
  runtime: ${file(../../common/config.yml):runtime}
  region: ${file(../../common/config.yml):region}
  stage: ${opt:stage,'dev'}
  logRetentionInDays: ${file(../../common/config.yml):logRetention}
  lambdaHashingVersion: 20201221
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  stackTags:
    Service: ${self:service}-${self:provider.stage}
  environment:
    stage: ${self:provider.stage}

resources:
  - ${file(resources/vpc.yml)}
  - Outputs:
      vpc:
        Value:
          Fn::GetAtt:
            - TestTable
            - Arn
        Export:
          Name: ${self:service}-${self:provider.stage}