Resources:
  EMRTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: 'PK'
          AttributeType: 'S'
        - AttributeName: 'SK'
          AttributeType: 'S'
        - AttributeName: 'RECTYPE'
          AttributeType: 'S'
      TimeToLiveSpecification:
        AttributeName: TimeToLive
        Enabled: true
      KeySchema:
        - AttributeName: 'PK'
          KeyType: 'HASH'
        - AttributeName: 'SK'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: GSI_1
          KeySchema:
            - AttributeName: SK
              KeyType: 'HASH'
          Projection:
            ProjectionType: ALL
        - IndexName: GSI_2
          KeySchema:
            - AttributeName: RECTYPE
              KeyType: 'HASH'
          Projection:
            ProjectionType: ALL