Resources:
  EMROutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          -
            AllowedOrigins:
              - '*'
            AllowedHeaders:
              - '*'
            AllowedMethods:
              - POST
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: ${self:custom.outputBucketName}
      LifecycleConfiguration:
        Rules:
          -
            ExpirationInDays: ${self:custom.expirationPolicy}
            Prefix: ''
            Status: Enabled
