service: ${file(../../common/config.yml):sevice}-s3

custom: ${file(stages/${self:provider.stage}.yml)}

package:
  individually: true

projectDir: ../../

provider:
  name: aws
  runtime: ${file(../../common/config.yml):runtime}
  region: ${file(../../common/config.yml):region}
  stage: ${opt:stage,'dev'}
  logRetentionInDays: 90
  lambdaHashingVersion: 20201221
  deploymentBucket:
    blockPublicAccess: true
    serverSideEncryption: AES256
  stackTags:
    Service: ${self:service}-${self:provider.stage}
  environment:
    stage: ${self:provider.stage}

resources:
  - ${file(resources/s3.yml)}
  - Outputs:
      s3BucketName:
        Value:
          Fn::GetAtt:
            - AwsSolutionsBucket
            - Arn
        Export:
          Name: ${self:service}-${self:provider.stage}